import {
  Student,
  Room,
  HostelBlock,
  Complaint,
  MaintenanceTask,
  Visitor,
  Outpass,
  RoomTransferRequest,
  EmergencyAlert,
  MessAttendanceData,
  HostelAnnouncement,
  AppNotification,
  AuditLogEntry,
  UserProfile,
} from '../types';

export const DEMO_USERS: Record<string, UserProfile> = {
  student: {
    id: 'usr_student_divya',
    name: 'Divya Gogineni',
    email: 'student@hostelhub.edu',
    role: 'STUDENT',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98765 43210',
    studentId: 'STU-2024-0302',
    room: 'A302',
    block: 'Block A',
  },
  warden: {
    id: 'usr_warden_sharma',
    name: 'Dr. Rameshwar Rao (Chief Warden)',
    email: 'warden@hostelhub.edu',
    role: 'WARDEN',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    phone: '+91 94401 23456',
  },
  security: {
    id: 'usr_security_singh',
    name: 'Vikram Singh (Head Security)',
    email: 'security@hostelhub.edu',
    role: 'SECURITY',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98111 88899',
  },
  maintenance: {
    id: 'usr_maint_ramesh',
    name: 'Ramesh Kumar (Lead Electrician)',
    email: 'maintenance@hostelhub.edu',
    role: 'MAINTENANCE',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98777 65432',
    specialization: 'Electrical & HVAC',
  },
  admin: {
    id: 'usr_admin_nizam',
    name: 'System Administrator',
    email: 'admin@hostelhub.edu',
    role: 'ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+91 99000 11223',
  },
};

export const INITIAL_BLOCKS: HostelBlock[] = [
  {
    id: 'blk_a',
    name: 'Block A',
    gender: 'FEMALE',
    floors: 4,
    totalRooms: 16,
    wardenName: 'Mrs. Lakshmi Devi',
    wardenPhone: '+91 94401 23451',
  },
  {
    id: 'blk_b',
    name: 'Block B',
    gender: 'FEMALE',
    floors: 4,
    totalRooms: 16,
    wardenName: 'Dr. Rameshwar Rao',
    wardenPhone: '+91 94401 23452',
  },
  {
    id: 'blk_c',
    name: 'Block C',
    gender: 'MALE',
    floors: 4,
    totalRooms: 16,
    wardenName: 'Prof. K. V. Raman',
    wardenPhone: '+91 94401 23453',
  },
];

export const INITIAL_ROOMS: Room[] = [
  // Block A Rooms
  { id: 'rm_a101', roomNumber: 'A101', block: 'Block A', floor: 1, capacity: 2, occupancy: 2, type: 'DOUBLE', status: 'FULL', amenities: ['WiFi', 'Attached Bath', 'Geyser', 'Balcony'], studentIds: ['stu_1', 'stu_2'], monthlyRent: 4500 },
  { id: 'rm_a102', roomNumber: 'A102', block: 'Block A', floor: 1, capacity: 2, occupancy: 2, type: 'DOUBLE', status: 'FULL', amenities: ['WiFi', 'Attached Bath', 'Geyser'], studentIds: ['stu_3', 'stu_4'], monthlyRent: 4500 },
  { id: 'rm_a103', roomNumber: 'A103', block: 'Block A', floor: 1, capacity: 2, occupancy: 1, type: 'DOUBLE', status: 'PARTIALLY_OCCUPIED', amenities: ['WiFi', 'Attached Bath'], studentIds: ['stu_5'], monthlyRent: 4500 },
  { id: 'rm_a104', roomNumber: 'A104', block: 'Block A', floor: 1, capacity: 2, occupancy: 0, type: 'DOUBLE', status: 'AVAILABLE', amenities: ['WiFi', 'Attached Bath', 'Geyser'], studentIds: [], monthlyRent: 4500 },

  { id: 'rm_a201', roomNumber: 'A201', block: 'Block A', floor: 2, capacity: 2, occupancy: 2, type: 'DOUBLE', status: 'FULL', amenities: ['WiFi', 'Attached Bath'], studentIds: ['stu_6', 'stu_7'], monthlyRent: 4500 },
  { id: 'rm_a202', roomNumber: 'A202', block: 'Block A', floor: 2, capacity: 2, occupancy: 2, type: 'DOUBLE', status: 'FULL', amenities: ['WiFi', 'Attached Bath'], studentIds: ['stu_8', 'stu_9'], monthlyRent: 4500 },
  { id: 'rm_a203', roomNumber: 'A203', block: 'Block A', floor: 2, capacity: 2, occupancy: 1, type: 'DOUBLE', status: 'PARTIALLY_OCCUPIED', amenities: ['WiFi', 'Attached Bath'], studentIds: ['stu_10'], monthlyRent: 4500 },
  { id: 'rm_a204', roomNumber: 'A204', block: 'Block A', floor: 2, capacity: 2, occupancy: 0, type: 'DOUBLE', status: 'AVAILABLE', amenities: ['WiFi', 'Attached Bath'], studentIds: [], monthlyRent: 4500 },

  { id: 'rm_a301', roomNumber: 'A301', block: 'Block A', floor: 3, capacity: 2, occupancy: 2, type: 'DOUBLE', status: 'FULL', amenities: ['WiFi', 'Attached Bath', 'AC'], studentIds: ['stu_11', 'stu_12'], monthlyRent: 5500 },
  { id: 'rm_a302', roomNumber: 'A302', block: 'Block A', floor: 3, capacity: 2, occupancy: 2, type: 'DOUBLE', status: 'FULL', amenities: ['WiFi', 'Attached Bath', 'AC', 'Balcony'], studentIds: ['stu_divya', 'stu_roommate'], monthlyRent: 5500 },
  { id: 'rm_a303', roomNumber: 'A303', block: 'Block A', floor: 3, capacity: 2, occupancy: 1, type: 'DOUBLE', status: 'PARTIALLY_OCCUPIED', amenities: ['WiFi', 'Attached Bath'], studentIds: ['stu_13'], monthlyRent: 4500 },
  { id: 'rm_a304', roomNumber: 'A304', block: 'Block A', floor: 3, capacity: 2, occupancy: 0, type: 'DOUBLE', status: 'MAINTENANCE', amenities: ['WiFi', 'Attached Bath'], studentIds: [], monthlyRent: 4500 },

  { id: 'rm_a401', roomNumber: 'A401', block: 'Block A', floor: 4, capacity: 1, occupancy: 1, type: 'SINGLE', status: 'FULL', amenities: ['WiFi', 'Attached Bath', 'AC'], studentIds: ['stu_14'], monthlyRent: 7000 },
  { id: 'rm_a402', roomNumber: 'A402', block: 'Block A', floor: 4, capacity: 2, occupancy: 2, type: 'DOUBLE', status: 'FULL', amenities: ['WiFi', 'Attached Bath'], studentIds: ['stu_15', 'stu_16'], monthlyRent: 4500 },
  { id: 'rm_a403', roomNumber: 'A403', block: 'Block A', floor: 4, capacity: 2, occupancy: 0, type: 'DOUBLE', status: 'AVAILABLE', amenities: ['WiFi', 'Attached Bath'], studentIds: [], monthlyRent: 4500 },
  { id: 'rm_a404', roomNumber: 'A404', block: 'Block A', floor: 4, capacity: 2, occupancy: 0, type: 'DOUBLE', status: 'AVAILABLE', amenities: ['WiFi', 'Attached Bath'], studentIds: [], monthlyRent: 4500 },

  // Block B Rooms
  { id: 'rm_b101', roomNumber: 'B101', block: 'Block B', floor: 1, capacity: 2, occupancy: 2, type: 'DOUBLE', status: 'FULL', amenities: ['WiFi', 'Attached Bath'], studentIds: ['stu_17', 'stu_18'], monthlyRent: 4500 },
  { id: 'rm_b102', roomNumber: 'B102', block: 'Block B', floor: 1, capacity: 2, occupancy: 2, type: 'DOUBLE', status: 'FULL', amenities: ['WiFi', 'Attached Bath'], studentIds: ['stu_19', 'stu_20'], monthlyRent: 4500 },
  { id: 'rm_b204', roomNumber: 'B204', block: 'Block B', floor: 2, capacity: 2, occupancy: 1, type: 'DOUBLE', status: 'PARTIALLY_OCCUPIED', amenities: ['WiFi', 'Attached Bath', 'Balcony'], studentIds: ['stu_priya'], monthlyRent: 4500 },
  { id: 'rm_b303', roomNumber: 'B303', block: 'Block B', floor: 3, capacity: 2, occupancy: 2, type: 'DOUBLE', status: 'FULL', amenities: ['WiFi', 'Attached Bath'], studentIds: ['stu_21', 'stu_22'], monthlyRent: 4500 },
  { id: 'rm_b110', roomNumber: 'B110', block: 'Block B', floor: 1, capacity: 2, occupancy: 2, type: 'DOUBLE', status: 'FULL', amenities: ['WiFi', 'Attached Bath', 'AC'], studentIds: ['stu_23', 'stu_24'], monthlyRent: 5500 },

  // Block C Rooms
  { id: 'rm_c101', roomNumber: 'C101', block: 'Block C', floor: 1, capacity: 2, occupancy: 1, type: 'DOUBLE', status: 'PARTIALLY_OCCUPIED', amenities: ['WiFi', 'Attached Bath'], studentIds: ['stu_neha'], monthlyRent: 4500 },
  { id: 'rm_c102', roomNumber: 'C102', block: 'Block C', floor: 1, capacity: 2, occupancy: 2, type: 'DOUBLE', status: 'FULL', amenities: ['WiFi', 'Attached Bath'], studentIds: ['stu_25', 'stu_26'], monthlyRent: 4500 },
  { id: 'rm_c201', roomNumber: 'C201', block: 'Block C', floor: 2, capacity: 2, occupancy: 2, type: 'DOUBLE', status: 'FULL', amenities: ['WiFi', 'Attached Bath'], studentIds: ['stu_27', 'stu_28'], monthlyRent: 4500 },
  { id: 'rm_c302', roomNumber: 'C302', block: 'Block C', floor: 3, capacity: 3, occupancy: 3, type: 'TRIPLE', status: 'FULL', amenities: ['WiFi', 'Common Bath'], studentIds: ['stu_29', 'stu_30', 'stu_31'], monthlyRent: 3500 },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'stu_divya',
    studentId: 'STU-2024-0302',
    name: 'Divya Gogineni',
    email: 'divya.g@hostelhub.edu',
    phone: '+91 98765 43210',
    gender: 'FEMALE',
    course: 'B.Tech Computer Science',
    year: '3rd Year',
    department: 'CSE',
    guardianName: 'Ravi Kumar Gogineni',
    guardianPhone: '+91 98765 43210',
    hostel: 'NN Student Residence',
    block: 'Block A',
    floor: 3,
    room: 'A302',
    admissionDate: '2023-08-15',
    status: 'ACTIVE',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    attendanceRate: 92,
    emergencyContact: '+91 98765 43210',
  },
  {
    id: 'stu_roommate',
    studentId: 'STU-2024-0303',
    name: 'Ananya Reddy',
    email: 'ananya.r@hostelhub.edu',
    phone: '+91 98480 12345',
    gender: 'FEMALE',
    course: 'B.Tech AI & Data Science',
    year: '3rd Year',
    department: 'AI-DS',
    guardianName: 'Krishna Reddy',
    guardianPhone: '+91 98480 99999',
    hostel: 'NN Student Residence',
    block: 'Block A',
    floor: 3,
    room: 'A302',
    admissionDate: '2023-08-15',
    status: 'ACTIVE',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    attendanceRate: 94,
    emergencyContact: '+91 98480 99999',
  },
  {
    id: 'stu_priya',
    studentId: 'STU-2024-0204',
    name: 'Priya Sharma',
    email: 'priya.s@hostelhub.edu',
    phone: '+91 98123 45678',
    gender: 'FEMALE',
    course: 'B.Tech Electronics & Comm',
    year: '2nd Year',
    department: 'ECE',
    guardianName: 'Anita Sharma',
    guardianPhone: '+91 98123 99988',
    hostel: 'NN Student Residence',
    block: 'Block B',
    floor: 2,
    room: 'B204',
    admissionDate: '2024-08-10',
    status: 'OUTSIDE',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    attendanceRate: 88,
    emergencyContact: '+91 98123 99988',
  },
  {
    id: 'stu_neha',
    studentId: 'STU-2024-0101',
    name: 'Neha Patel',
    email: 'neha.p@hostelhub.edu',
    phone: '+91 97234 56789',
    gender: 'FEMALE',
    course: 'B.Tech Information Tech',
    year: '1st Year',
    department: 'IT',
    guardianName: 'Suresh Patel',
    guardianPhone: '+91 97234 11223',
    hostel: 'NN Student Residence',
    block: 'Block C',
    floor: 1,
    room: 'C101',
    admissionDate: '2025-08-01',
    status: 'ACTIVE',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    attendanceRate: 95,
    emergencyContact: '+91 97234 11223',
  },
  {
    id: 'stu_1',
    studentId: 'STU-2024-0102',
    name: 'Sneha Rao',
    email: 'sneha.r@hostelhub.edu',
    phone: '+91 98765 11111',
    gender: 'FEMALE',
    course: 'B.Tech Mechanical',
    year: '2nd Year',
    department: 'ME',
    guardianName: 'Venkat Rao',
    guardianPhone: '+91 98765 22222',
    hostel: 'NN Student Residence',
    block: 'Block A',
    floor: 1,
    room: 'A101',
    admissionDate: '2024-08-10',
    status: 'ACTIVE',
    photo: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    attendanceRate: 91,
    emergencyContact: '+91 98765 22222',
  },
  {
    id: 'stu_2',
    studentId: 'STU-2024-0103',
    name: 'Kavita Verma',
    email: 'kavita.v@hostelhub.edu',
    phone: '+91 98765 33333',
    gender: 'FEMALE',
    course: 'B.Tech Civil Engg',
    year: '3rd Year',
    department: 'CE',
    guardianName: 'Ramesh Verma',
    guardianPhone: '+91 98765 44444',
    hostel: 'NN Student Residence',
    block: 'Block A',
    floor: 1,
    room: 'A101',
    admissionDate: '2023-08-15',
    status: 'ACTIVE',
    photo: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=150&auto=format&fit=crop&q=80',
    attendanceRate: 89,
    emergencyContact: '+91 98765 44444',
  },
  {
    id: 'stu_14',
    studentId: 'STU-2024-0401',
    name: 'Meghana Joshi',
    email: 'meghana.j@hostelhub.edu',
    phone: '+91 98765 55555',
    gender: 'FEMALE',
    course: 'M.Tech CSE',
    year: '1st Year',
    department: 'CSE',
    guardianName: 'Sunil Joshi',
    guardianPhone: '+91 98765 66666',
    hostel: 'NN Student Residence',
    block: 'Block A',
    floor: 4,
    room: 'A401',
    admissionDate: '2025-08-01',
    status: 'ACTIVE',
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    attendanceRate: 96,
    emergencyContact: '+91 98765 66666',
  },
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'CMP-2026-00125',
    studentId: 'stu_divya',
    studentName: 'Divya Gogineni',
    studentRoom: 'A302',
    studentBlock: 'Block A',
    category: 'Electrical',
    title: 'Fan not working properly',
    description: 'Ceiling fan makes loud grinding noise and stops rotating after 5 minutes of running on speed 3.',
    location: 'Block A • 3rd Floor • Room A302',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    photoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
    createdAt: '2026-09-16T10:20:00Z',
    updatedAt: '2026-09-16T10:45:00Z',
    slaDeadline: new Date(Date.now() + 14 * 3600 * 1000).toISOString(),
    slaHoursTotal: 24,
    assignedStaffId: 'usr_maint_ramesh',
    assignedStaffName: 'Ramesh Kumar (Electrician)',
    beforePhotoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
  },
  {
    id: 'CMP-2026-00126',
    studentId: 'stu_priya',
    studentName: 'Priya Sharma',
    studentRoom: 'B204',
    studentBlock: 'Block B',
    category: 'Plumbing',
    title: 'Water leakage under washbasin',
    description: 'Washbasin pipe joint in bathroom has continuous leakage creating water puddle on floor.',
    location: 'Block B • 2nd Floor • Room B204',
    priority: 'HIGH',
    status: 'ASSIGNED',
    photoUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=500&auto=format&fit=crop&q=80',
    createdAt: '2026-09-16T11:30:00Z',
    updatedAt: '2026-09-16T11:45:00Z',
    slaDeadline: new Date(Date.now() + 3 * 3600 * 1000).toISOString(),
    slaHoursTotal: 6,
    assignedStaffId: 'usr_maint_suresh',
    assignedStaffName: 'Suresh Plumber',
  },
  {
    id: 'CMP-2026-00127',
    studentId: 'stu_neha',
    studentName: 'Neha Patel',
    studentRoom: 'C101',
    studentBlock: 'Block C',
    category: 'Electrical',
    title: 'Light not working in study desk area',
    description: 'Tube light over the study table is flickering and turns off automatically.',
    location: 'Block C • 1st Floor • Room C101',
    priority: 'MEDIUM',
    status: 'RESOLVED',
    photoUrl: 'https://images.unsplash.com/photo-1507499739999-097706ad8914?w=500&auto=format&fit=crop&q=80',
    createdAt: '2026-09-15T14:15:00Z',
    updatedAt: '2026-09-16T09:30:00Z',
    slaDeadline: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
    slaHoursTotal: 24,
    assignedStaffId: 'usr_maint_ramesh',
    assignedStaffName: 'Ramesh Kumar (Electrician)',
    resolutionNotes: 'LED driver and tube starter replaced with new Philips unit.',
    beforePhotoUrl: 'https://images.unsplash.com/photo-1507499739999-097706ad8914?w=500&auto=format&fit=crop&q=80',
    afterPhotoUrl: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=500&auto=format&fit=crop&q=80',
    resolvedAt: '2026-09-16T09:30:00Z',
  },
  {
    id: 'CMP-2026-00128',
    studentId: 'stu_14',
    studentName: 'Meghana Joshi',
    studentRoom: 'A401',
    studentBlock: 'Block A',
    category: 'AC',
    title: 'AC not cooling properly',
    description: 'Split AC is blowing warm air even at 18 degrees Celsius setting.',
    location: 'Block A • 4th Floor • Room A401',
    priority: 'LOW',
    status: 'SUBMITTED',
    photoUrl: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=500&auto=format&fit=crop&q=80',
    createdAt: '2026-09-16T14:45:00Z',
    updatedAt: '2026-09-16T14:45:00Z',
    slaDeadline: new Date(Date.now() + 48 * 3600 * 1000).toISOString(),
    slaHoursTotal: 48,
  },
  {
    id: 'CMP-2026-00129',
    studentId: 'stu_roommate',
    studentName: 'Ananya Reddy',
    studentRoom: 'A302',
    studentBlock: 'Block A',
    category: 'Internet',
    title: 'WiFi access point weak signal',
    description: 'HostelHub-BlockA-5G shows 1 bar signal inside A302 intermittently.',
    location: 'Block A • 3rd Floor • Corridor A3',
    priority: 'MEDIUM',
    status: 'SUBMITTED',
    createdAt: '2026-09-16T08:00:00Z',
    updatedAt: '2026-09-16T08:00:00Z',
    slaDeadline: new Date(Date.now() + 20 * 3600 * 1000).toISOString(),
    slaHoursTotal: 24,
  },
  {
    id: 'CMP-2026-00120',
    studentId: 'stu_1',
    studentName: 'Sneha Rao',
    studentRoom: 'A101',
    studentBlock: 'Block A',
    category: 'Cleaning',
    title: 'Corridor dustbin overflow',
    description: 'Dustbin on 1st floor near stairs needs clearing.',
    location: 'Block A • 1st Floor',
    priority: 'LOW',
    status: 'RESOLVED',
    createdAt: '2026-09-15T09:00:00Z',
    updatedAt: '2026-09-15T11:00:00Z',
    slaDeadline: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    slaHoursTotal: 24,
    resolutionNotes: 'Cleaned and sanitized.',
    resolvedAt: '2026-09-15T11:00:00Z',
  },
];

export const INITIAL_MAINTENANCE_TASKS: MaintenanceTask[] = [
  {
    id: 'TSK-001',
    complaintId: 'CMP-2026-00125',
    title: 'Fan not working properly',
    location: 'Block A • 3rd Floor • Room A302',
    category: 'Electrical',
    priority: 'HIGH',
    slaDeadline: new Date(Date.now() + 14 * 3600 * 1000).toISOString(),
    assignedToId: 'usr_maint_ramesh',
    assignedToName: 'Ramesh Kumar',
    assignedToRole: 'Lead Electrician',
    status: 'IN_PROGRESS',
    startedAt: '10:20 AM',
    beforePhoto: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
    createdAt: '2026-09-16T10:20:00Z',
  },
  {
    id: 'TSK-002',
    complaintId: 'CMP-2026-00126',
    title: 'Water leakage under washbasin',
    location: 'Block B • 2nd Floor • Room B204',
    category: 'Plumbing',
    priority: 'HIGH',
    slaDeadline: new Date(Date.now() + 3 * 3600 * 1000).toISOString(),
    assignedToId: 'usr_maint_ramesh',
    assignedToName: 'Ramesh Kumar',
    assignedToRole: 'Lead Electrician',
    status: 'ASSIGNED',
    createdAt: '2026-09-16T11:30:00Z',
  },
  {
    id: 'TSK-003',
    complaintId: 'CMP-2026-00127',
    title: 'Light not working in study desk area',
    location: 'Block C • 1st Floor • Room C101',
    category: 'Electrical',
    priority: 'MEDIUM',
    slaDeadline: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
    assignedToId: 'usr_maint_ramesh',
    assignedToName: 'Ramesh Kumar',
    assignedToRole: 'Lead Electrician',
    status: 'COMPLETED',
    startedAt: '08:45 AM',
    completedAt: '09:30 AM',
    beforePhoto: 'https://images.unsplash.com/photo-1507499739999-097706ad8914?w=500&auto=format&fit=crop&q=80',
    afterPhoto: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=500&auto=format&fit=crop&q=80',
    resolutionNotes: 'Replaced faulty choke and fitted standard daylight tube.',
    createdAt: '2026-09-15T14:15:00Z',
  },
];

export const INITIAL_VISITORS: Visitor[] = [
  {
    id: 'VIS-2026-081',
    studentId: 'stu_divya',
    studentName: 'Divya Gogineni',
    studentRoom: 'A302',
    visitorName: 'Ravi Kumar Gogineni',
    relationship: 'Father',
    phoneNumber: '9876543210',
    visitDate: '2026-09-17',
    visitTime: '5:00 PM',
    purpose: 'Meet student and deliver family essentials',
    status: 'APPROVED',
    qrCodeData: 'HOSTELHUB:VIS:VIS-2026-081:DIVYA:A302',
    approvedBy: 'Dr. Rameshwar Rao (Warden)',
    createdAt: '2026-09-16T09:00:00Z',
  },
  {
    id: 'VIS-2026-080',
    studentId: 'stu_priya',
    studentName: 'Priya Sharma',
    studentRoom: 'B204',
    visitorName: 'Anita Sharma',
    relationship: 'Mother',
    phoneNumber: '9812399988',
    visitDate: '2026-09-16',
    visitTime: '4:00 PM',
    purpose: 'Medical checkup pickup',
    status: 'CHECKED_OUT',
    checkedInAt: '4:12 PM',
    checkedOutAt: '4:40 PM',
    qrCodeData: 'HOSTELHUB:VIS:VIS-2026-080:PRIYA:B204',
    createdAt: '2026-09-16T08:30:00Z',
  },
  {
    id: 'VIS-2026-079',
    studentId: 'stu_neha',
    studentName: 'Neha Patel',
    studentRoom: 'C101',
    visitorName: 'Suresh Patel',
    relationship: 'Brother',
    phoneNumber: '9723411223',
    visitDate: '2026-09-16',
    visitTime: '3:00 PM',
    purpose: 'Laptop handover',
    status: 'CHECKED_IN',
    checkedInAt: '3:15 PM',
    qrCodeData: 'HOSTELHUB:VIS:VIS-2026-079:NEHA:C101',
    createdAt: '2026-09-16T07:45:00Z',
  },
];

export const INITIAL_OUTPASSES: Outpass[] = [
  {
    id: 'OUT-2026-0194',
    studentId: 'stu_divya',
    studentName: 'Divya Gogineni',
    studentRoom: 'A302',
    studentBlock: 'Block A',
    studentPhone: '+91 98765 43210',
    fromDateTime: '2026-09-20T16:00',
    toDateTime: '2026-09-22T19:00',
    destination: 'Home (Hyderabad)',
    reason: 'Attending cousin family function and wedding ceremony',
    status: 'APPROVED',
    qrCodeData: 'HOSTELHUB:OUT:OUT-2026-0194:DIVYA:2026-09-20',
    parentContacted: true,
    approvedBy: 'Dr. Rameshwar Rao (Warden)',
    createdAt: '2026-09-16T11:00:00Z',
  },
  {
    id: 'OUT-2026-0193',
    studentId: 'stu_priya',
    studentName: 'Priya Sharma',
    studentRoom: 'B204',
    studentBlock: 'Block B',
    studentPhone: '+91 98123 45678',
    fromDateTime: '2026-09-16T14:00',
    toDateTime: '2026-09-16T20:00',
    destination: 'City Market / Hospital',
    reason: 'Dentist appointment',
    status: 'ACTIVE_OUT',
    actualExitTime: '2:15 PM',
    qrCodeData: 'HOSTELHUB:OUT:OUT-2026-0193:PRIYA:2026-09-16',
    parentContacted: true,
    approvedBy: 'Dr. Rameshwar Rao (Warden)',
    createdAt: '2026-09-15T18:00:00Z',
  },
];

export const INITIAL_ROOM_TRANSFERS: RoomTransferRequest[] = [
  {
    id: 'TRF-001',
    studentId: 'stu_divya',
    studentName: 'Divya Gogineni',
    currentRoom: 'A302',
    currentBlock: 'Block A',
    requestedRoom: 'B204',
    requestedBlock: 'Block B',
    reason: 'Roommate study hours discrepancy and seeking closer room to library wing',
    additionalNote: 'I would like to transfer due to study schedule alignment.',
    status: 'PENDING',
    createdAt: '2026-09-16T12:00:00Z',
  },
];

export const INITIAL_EMERGENCIES: EmergencyAlert[] = [
  {
    id: 'EMG-2026-004',
    studentId: 'stu_14',
    studentName: 'Meghana Joshi',
    studentRoom: 'A401',
    studentBlock: 'Block A',
    studentFloor: 4,
    emergencyType: 'Electrical',
    status: 'RESOLVED',
    message: 'Electrical spark reported near AC switch board',
    createdAt: '2026-09-14T16:20:00Z',
    acknowledgedBy: 'Vikram Singh (Head Security)',
    acknowledgedAt: '2026-09-14T16:22:00Z',
    resolvedAt: '2026-09-14T16:50:00Z',
    actionTaken: 'Power tripped at MCB box, wiring renewed by Ramesh Kumar.',
  },
];

export const INITIAL_MESS_DATA: MessAttendanceData = {
  date: '2026-09-16',
  totalResidents: 500,
  currentlyOutside: 65,
  breakfastExpected: 410,
  lunchExpected: 435,
  dinnerExpected: 430,
  breakfastServed: 395,
  lunchServed: 422,
  dinnerServed: 415,
  menu: {
    breakfast: ['Idli & Medu Vada', 'Sambar', 'Coconut Chutney', 'Boiled Eggs', 'Tea / Coffee / Milk'],
    lunch: ['Paneer Butter Masala', 'Dal Tadka', 'Jeera Rice', 'Phulka', 'Curd & Salad', 'Gulab Jamun'],
    dinner: ['Aloo Gobi Dry', 'Mixed Veg Curry', 'Chapati', 'Steamed Rice', 'Rasam', 'Seasonal Fruit'],
  },
};

export const INITIAL_ANNOUNCEMENTS: HostelAnnouncement[] = [
  {
    id: 'ANN-001',
    title: 'Hostel Night & Nizamabad Hackathon Celebration 2026',
    message: 'All residents are invited to the main auditorium on Friday 7:00 PM. Special dinner will be served at 8:30 PM.',
    audience: 'All Students',
    priority: 'HIGH',
    date: '16 Sep 2026',
    authorName: 'Dr. Rameshwar Rao (Chief Warden)',
  },
  {
    id: 'ANN-002',
    title: 'Routine Water Tank Cleaning - Block B & C',
    message: 'Water supply will be temporarily paused between 1:00 PM and 3:30 PM tomorrow for sanitization.',
    audience: 'Block B',
    priority: 'NORMAL',
    date: '15 Sep 2026',
    authorName: 'Hostel Maintenance Wing',
  },
  {
    id: 'ANN-003',
    title: 'Strict Biometric & QR Outpass Verification at Main Gate',
    message: 'Security staff will strictly verify Approved Outpass QR codes after 8:00 PM. Please ensure approval from Warden in advance.',
    audience: 'All Students',
    priority: 'URGENT',
    date: '14 Sep 2026',
    authorName: 'Vikram Singh (Head Security)',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'NOTIF-01',
    recipientId: 'stu_divya',
    title: 'Outpass Approved',
    message: 'Your outpass request to Home for Sep 20-22 has been approved by Warden.',
    type: 'OUTPASS',
    read: false,
    timestamp: '10 mins ago',
  },
  {
    id: 'NOTIF-02',
    recipientId: 'stu_divya',
    title: 'Visitor Request Approved',
    message: 'Ravi Kumar (Father) visit scheduled for 17 Sep 5:00 PM is approved.',
    type: 'VISITOR',
    read: false,
    timestamp: '1 hour ago',
  },
  {
    id: 'NOTIF-03',
    recipientId: 'stu_divya',
    title: 'Complaint Assigned',
    message: 'Your fan complaint CMP-2026-00125 has been assigned to Ramesh (Electrician).',
    type: 'COMPLAINT',
    read: true,
    timestamp: '3 hours ago',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'AUD-001',
    actor: 'Dr. Rameshwar Rao',
    role: 'WARDEN',
    action: 'Approved Outpass',
    target: 'OUT-2026-0194 (Divya Gogineni)',
    timestamp: '2026-09-16 11:05 AM',
    details: 'Verified with parent consent',
  },
  {
    id: 'AUD-002',
    actor: 'Dr. Rameshwar Rao',
    role: 'WARDEN',
    action: 'Assigned Maintenance Task',
    target: 'CMP-2026-00125 to Ramesh Kumar',
    timestamp: '2026-09-16 10:20 AM',
    details: 'SLA set to 24 hrs',
  },
  {
    id: 'AUD-003',
    actor: 'Vikram Singh',
    role: 'SECURITY',
    action: 'Checked Out Visitor',
    target: 'VIS-2026-080 (Anita Sharma)',
    timestamp: '2026-09-16 04:40 PM',
  },
  {
    id: 'AUD-004',
    actor: 'Divya Gogineni',
    role: 'STUDENT',
    action: 'Raised Complaint',
    target: 'CMP-2026-00125 (Fan not working)',
    timestamp: '2026-09-16 10:20 AM',
  },
];
